### ISSUE TITLE
Cannot load module

### ISSUE THREAD

**Issue by slesinger** [bruxy70/CzPubTran#7]
Hello,

I am getting error when starting Home Assistant:

  File "/home/hass/.homeassistant/custom_components/cz_pub_tran/__init__.py", line 6, in <module>
    from czpubtran.api import czpubtran
  File "<fstring>", line 1
    (await combination_response.text())

I had to manually install czpubtran module by command:
```pip install czpubtran```
(Module did not install automatically by HA)
Version install 0.1.20

I tried to load from python interactive shell from a correct virtual env:
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import czpubtran
>>> from czpubtran.api import czpubtran
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<fstring>", line 1
    (await combination_response.text())
                              ^
SyntaxError: invalid syntax
```
Error happens when loadig specifically czpubtran.api.
My HA version is 0.99.3
Thank you.

PS: Nebydlite nekde pobliz? Ja jsem z Lipencu.
Zdravi
  Honza

**Comment by bruxy70** [comment]
I think this is an issue with the [component](https://github.com/bruxy70/CZ-Public-Transport), not with this package. I have pushed a version 1.10 that hopefully fixes that. Can you please update and see if that works?
P.S. Tak nejsme sousedi, ale pobliz to asi je - Chyne.
V

**Comment by slesinger** [comment]
Ahoj,

the above mentioned bug is gone:
```
2019-10-07 18:59:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for cz_pub_tran which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```
Component is loaded. However the whole HA refuses to start . These are only errors in the HA log. The log also does not output anything else:
```
2019-10-07 18:59:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-10-07 18:59:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-10-07 18:59:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 417, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 637, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
When I remove the cz_pub_tran configuration from configuration.yaml its starts just normal. 
Here is my relevant part of configuration.yaml :
```
cz_pub_tran:
  sensors:
    - origin: "Škola Lipence"
      destination: "Zbraslavské náměstí"
      name: 'na namesti'
    - origin: "Zbraslavské náměstí"
      destination: "Škola Lipence"
      name: 'z namesti'
    - origin: "Smíchovské nádraží"
      destination: "Škola Lipence"
      name: 'ze Smícháce'
```
Thanks for your support.
H.

**Comment by bruxy70** [comment]
The configuration looks ok. I have tried that and it worked fine. 
Can you try to enable debug if it shows more.
```
logs:
  custom_components.cz_pub_tran: debug
  czpubtran: debug
```

**Comment by slesinger** [comment]
I have enabled the log but there is no new entry in the log when restarting using systemd. When I start using ```hass``` command from homeasssitant virtualenv, I get this log:
```
2019-10-07 22:27:37 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-10-07 22:27:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-10-07 22:27:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-10-07 22:27:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
/usr/lib/python3.6/asyncio/base_events.py:509: RuntimeWarning: coroutine 'async_load_platform' was never awaited
  self._ready.clear()
Traceback (most recent call last):
  File "/home/hass/homeassistant/bin/hass", line 10, in <module>
    sys.exit(main())
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/__main__.py", line 401, in main
    exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/util/async_.py", line 37, in asyncio_run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/__main__.py", line 304, in setup_and_run_hass
    log_no_color=args.log_no_color,
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/bootstrap.py", line 150, in async_from_config_file
    config_dict, hass, enable_log=False, skip_pip=skip_pip
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/bootstrap.py", line 95, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/bootstrap.py", line 376, in _async_set_up_integrations
    *(async_setup_component(hass, domain, config) for domain in domains_to_load)
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 52, in async_setup_component
    return await task  # type: ignore
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 137, in _async_setup_component
    hass, config, integration
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/config.py", line 715, in async_process_component_config
    component = integration.get_component()
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 223, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hass/.homeassistant/custom_components/cz_pub_tran/__init__.py", line 6, in <module>
    from czpubtran.api import czpubtran
  File "<fstring>", line 1
    (await combination_response.text())
                              ^
SyntaxError: invalid syntax
2019-10-07 22:27:39 ERROR (SyncWorker_17) [concurrent.futures] exception calling callback for <Future at 0x7fda212d6400 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 417, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 637, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
That is again the same bug.
Thank you

**Comment by bruxy70** [comment]
Found it! Apparently, the await expressions in f-strings are only available in python from 3.7. You have 3.6, that's why it reports a syntax error.
Let me re-write it to be compatible with 3.6

**Comment by bruxy70** [comment]
Ok, please upgrade the component (v1.11), it should automatically upgrade the czpubtran module to v0.1.21 that should fix the issue. Let me know. Thanks.

**Comment by slesinger** [comment]
Thanks a lot. Issue confirmed fixed. :-)
